FLAKE_DIR := "."
[private]
_nix := "nix --extra-experimental-features 'nix-command flakes'"

update:
    {{ _nix }} flake update

show:
    {{ _nix }} flake show {{ FLAKE_DIR }}

switch host:
    @if [ ! -f "$HOME/.ssh/ssh_identity" ] || [ ! -f "$HOME/.ssh/ssh_identity.pub" ]; then \
      echo "Warning: Missing ~/.ssh/ssh_identity or ~/.ssh/ssh_identity.pub"; \
      exit 1; \
    fi
    @echo "==> Applying host {{ host }} using flake at {{ FLAKE_DIR }}"
    {{ _nix }} run --accept-flake-config "{{ FLAKE_DIR }}#hm" -- \
      switch --flake "{{ FLAKE_DIR }}#{{ host }}" -b backup

    just clean

clean:
    @echo "==> Cleaning up old generations"
    {{ _nix }} profile wipe-history --older-than 14d || true
    nix-collect-garbage --delete-older-than 14d || true

optimise:
    @echo "==> Optimising and deduplicating nix store"
    {{ _nix }} store optimise
