{
  config,
  pkgs,
  lib,
  ...
}:

let
  inherit (pkgs.stdenv.hostPlatform) isDarwin;
  enabled = config.my.gpu.backend != "none";

  # Tabby always talks to one OpenAI-compatible completion endpoint on :8082,
  # but what serves it differs by host. Docker on macOS has no Metal
  # passthrough, so a containerised llama-server there would be CPU-only;
  # darwin runs it natively on loopback instead. Linux runs it as a compose
  # service in AI/tabby.yaml that owns the `fim` network alias.
  # No /v1 suffix: llama.cpp/completion posts to llama-server's native
  # /completion, not the OpenAI-shaped /v1/completions.
  completionEndpoint =
    if isDarwin then "http://127.0.0.1:8082" else "http://fim:8082";

  # SPM ordering, verified against both Mellum models (same tokenizer family:
  # <fim_prefix>/<fim_suffix>/<fim_middle> at ids 8/10/9).
  #
  # Mellum-4b requires SPM: under PSM it discards the suffix entirely and
  # regenerates the whole enclosing function instead of infilling -- plausible
  # code answering the wrong question, which reads as a bad model rather than a
  # bad template. Mellum2 accepts either ordering identically, matching its
  # report's 50/50 PSM/SPM training mix. SPM is therefore correct for both.
  mellumTemplate = "<fim_suffix>{suffix}<fim_prefix>{prefix}<fim_middle>";
  qwenTemplate = "<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>";

  # Tabby's prompt_template exposes only {prefix}/{suffix}, so Mellum never
  # receives the <filename> token its multi-file context format is built
  # around; cross-file snippets arrive folded into the prefix as comments.
  # Results here understate Mellum relative to JetBrains' published numbers.
  # kind must be one the *pinned* Tabby understands, not whatever the current
  # docs advertise: nixpkgs-tabby holds 0.28.0, whose binary contains no
  # "vllm/completion" string at all. Configuring an unknown kind is not a hard
  # error -- Tabby starts clean and simply never issues a completion request,
  # which looks like a dead editor rather than a config problem.
  # 0.28.0 knows llama.cpp/completion, openai/completion and mistral/completion.
  mkCompletionConfig = promptTemplate: ''
    # Generated by nix/modules/ai/tabby.nix -- edit that, not this.
    [model.completion.http]
    kind = "llama.cpp/completion"
    api_endpoint = "${completionEndpoint}"
    # Unused by the llama.cpp backend (the server holds exactly one model), but
    # present because Tabby's documented schema for this kind includes it.
    model_name = "fim"
    prompt_template = "${promptTemplate}"
  '';

  completionConfigs = {
    qwen = mkCompletionConfig qwenTemplate;
    mellum = mkCompletionConfig mellumTemplate;
    mellum2 = mkCompletionConfig mellumTemplate;
  };

  defaultModel = "mellum";

  # Installed as real files rather than home.file symlinks: on Linux ~/.tabby
  # is bind-mounted into the Tabby container as /data, where a symlink into
  # /nix/store would dangle.
  installConfigs = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (name: text: ''
      $DRY_RUN_CMD install -m 0644 ${pkgs.writeText "tabby-${name}.toml" text} \
        "$HOME/.tabby/configs/${name}.toml"
    '') completionConfigs
  );
in
lib.mkIf enabled {
  home.activation.tabbyCompletionConfigs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p "$HOME/.tabby/configs"
    ${installConfigs}

    # config.toml points at one of the above. Relative so it also resolves
    # inside the container, where both ends sit under the /data mount. Seeded
    # once and then left alone: which model is active is runtime state owned
    # by nvim's picker, not something to reset on every home-manager switch.
    if [ ! -e "$HOME/.tabby/config.toml" ]; then
      $DRY_RUN_CMD ln -sfn "configs/${defaultModel}.toml" "$HOME/.tabby/config.toml"
    fi
  '';
}
