# -----------------------------------------------------------------------------
# Kanagawa Paper Canvas
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-canvas.toml
# URL: https://wezterm.org/config/appearance.html
# -----------------------------------------------------------------------------

[colors]
foreground = "#62666a"
background = "#e1e1de"
cursor_bg = "#6b7a95"
cursor_border = "#6b7a95"
cursor_fg = "#e1e1de"
selection_bg = "#b4aeb4"
selection_fg = "#62666a"
split = "#8489a2"
compose_cursor = "#6b7a95"
scrollbar_thumb = "#cbc8bc"

ansi = [
  "#79756d",
  "#a56461",
  "#697f79",
  "#8e7f5a",
  "#6d848e",
  "#866b81",
  "#6b7a95",
  "#94948d",
]
brights = [
  "#868279",
  "#b66f6c",
  "#748c85",
  "#9b8b63",
  "#829da8",
  "#95778f",
  "#7687a4",
  "#9e9e97",
]

[colors.indexed]
16 = "#977865"
17 = "#a56461"

[colors.tab_bar]
background = "#d1cfc5"
inactive_tab_edge = "#6b7a95"

[colors.tab_bar.active_tab]
fg_color = "#6b7a95"
bg_color = "#e1e1de"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#79756d"
bg_color = "#d1cfc5"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#866b81"
bg_color = "#e1e1de"

[colors.tab_bar.new_tab]
fg_color = "#79756d"
bg_color = "#d1cfc5"

[colors.tab_bar.new_tab_hover]
fg_color = "#866b81"
bg_color = "#e1e1de"
intensity = "Bold"

[metadata]
name = "kanagawa-paper-canvas"
author = "Simon Ho"
origin_url = "https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-canvas.toml"
