name: Build Devcontainer
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 2' # Every Tuesday at 12:00 UTC (4:00 AM PST/PDT)
jobs:
  build:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: write
    env:
      GH_USER: ${{ github.actor }}
      GH_GHCR: ${{ secrets.GH_GHCR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Run Makefile to build and push prebuild image
        run: make -C .devcontainer build push clean
      - name: Delete old GHCR image versions
        env:
          GH_TOKEN: ${{ secrets.GH_GHCR }}
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/devcontainer-prebuild"
          KEEP=5

          # Get all version IDs sorted by date (newest first), then skip the newest $KEEP
          versions=$(gh api -H "Accept: application/vnd.github+json" \
            "/user/packages/container/devcontainer-prebuild/versions" |
            jq 'sort_by(.created_at) | reverse | .[].id' | tail -n +$((KEEP + 1)))

          for version_id in $versions; do
            echo "Deleting image version ID: $version_id"
            gh api --method DELETE "/user/packages/container/devcontainer-prebuild/versions/$version_id"
          done
